jar 'asd:asd:123' do
  scope 'test'
  classifier 'source'
  exclusions 'group:a1', ['group','a2'] do
    exclusion 'group', 'a3'
    exclusion :artifact_id => 'a4', :group_id => 'group'
    exclusion 'group:a5'
    exclusion 'group' do
      artifact_id 'a6'
    end
    exclusion do
      group_id 'group'
      artifact_id 'a7'
    end
  end
end
jar 'dsa:dsa', '12', :exclusions => ['group:b1', ['group','b2']], :classifier => 'provided' do
  exclusion 'group:b3'
end
