#-*- mode: ruby -*-

source 'https://rubygems.org'
ruby '1.9.3', engine: 'jruby', engine_version: '1.7.12'

gem 'rack',                           '~> 1.5.2'
gem 'activerecord',                   '~> 4.1.1'
gem 'activerecord-jdbcmysql-adapter', '~> 1.3.7'
gem 'newrelic_rpm'
gem 'aws-sdk',                        '~> 1.40.2'
gem 'grape',                          '~> 0.7.0'

group :test do
  gem 'codeclimate-test-reporter',                  require: false
  gem 'rspec-mocks',                 '~> 2.14.1'
  gem 'rspec',                       '~> 2.14.1'
  gem 'simplecov',                   '~> 0.8.2',    require: false
  gem 'thor',                        '~> 0.18.1',   require: false
  gem 'vcr',                         '~> 2.8.0'
  gem 'webmock',                     '~> 1.16.0'
  gem 'fake_sqs',                    '~> 0.1.0'
  gem 'rack-test',                   '~> 0.6.2'
  gem 'database_cleaner',            '~> 1.2.0'
  gem 'shoulda-matchers',            '~> 2.6.1'
end

# vim: syntax=Ruby
