SRCS = ACssPauseAfter.java ACssProperty.java\
ACssCue.java ACssPauseBefore.java ACssSpeechRate.java\
ACssCueAfter.java ACssPitch.java ACssStyle.java\
ACssCueBefore.java ACssPlayDuring.java ACssVoiceFamily.java\
ACssPause.java ACssProperties.java ACssVolume.java\
ACssSpeakPunctuation.java ACssSpeakDate.java\
ACssSpeakNumeral.java ACssSpeakTime.java\
ACssRichness.java ACssStress.java\
ACssPitchRange.java ACssElevation.java\
ACssAzimuth.java

OBJS = $(SRCS:.java=.class)

PACKAGE = org.w3c.css.aural
JAVAC = javac
JAVADOC = javadoc
JAVADOCFLAGS = -version -d docs -protected
JAVACFLAGS = 
MAKEDEPEND = jmakedepend

.SUFFIXES: .class .java
.java.class:; $(JAVAC) $(JAVACFLAGS) $<

all: $(OBJS)

javadoc:; $(JAVADOC) $(JAVADOCFLAGS) $(PACKAGE)

clean:; -rm -f $(OBJS) *~ core

depend:; $(MAKEDEPEND) $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
ACssPitchRange.class:: ACssPitchRange.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssProperty.class:: ACssProperty.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class
ACssCueBefore.class:: ACssCueBefore.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssURL.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class
ACssSpeakDate.class:: ACssSpeakDate.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssPitch.class:: ACssPitch.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssFrequency.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssRichness.class:: ACssRichness.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssPauseBefore.class:: ACssPauseBefore.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssTime.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssSpeechRate.class:: ACssSpeechRate.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssStyle.class:: ACssStyle.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Warnings.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Warning.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/Css1Style.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class
ACssPlayDuring.class:: ACssPlayDuring.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssURL.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class\
	/usr/local/java11/bin/../lib/classes.zip
ACssProperties.class:: ACssProperties.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class
ACssSpeakPunctuation.class:: ACssSpeakPunctuation.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssPauseAfter.class:: ACssPauseAfter.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssTime.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssStress.class:: ACssStress.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssCueAfter.class:: ACssCueAfter.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssURL.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class
ACssAzimuth.class:: ACssAzimuth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssAngle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssElevation.class:: ACssElevation.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssAngle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssVoiceFamily.class:: ACssVoiceFamily.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssString.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Util.class
ACssSpeakNumeral.class:: ACssSpeakNumeral.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssCue.class:: ACssCue.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssVolume.class:: ACssVolume.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssPause.class:: ACssPause.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
ACssSpeakTime.class:: ACssSpeakTime.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.properties/CssProperty.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
