package com.aptana.editor.common.scripting.commands;

public enum VARIABLES_NAMES {
	TM_BUNDLE_SUPPORT
	,TM_CURRENT_LINE
	,TM_CURRENT_WORD
	,TM_DIRECTORY
	,TM_FILEPATH
	,TM_FILENAME
	,TM_LINE_NUMBER
	,TM_LINE_INDEX
	,TM_PROJECT_DIRECTORY
	,TM_SCOPE
	,TM_SELECTED_FILES
	,TM_SELECTED_FILE
	,TM_SELECTED_TEXT
	,TM_SOFT_TABS
	,TM_SUPPORT_PATH
	,TM_TAB_SIZE
	
	,TM_SELECTION_OFFSET
	,TM_SELECTION_LENGTH
	,TM_SELECTION_START_LINE_NUMBER
	,TM_SELECTION_END_LINE_NUMBER
	,TM_CARET_LINE_NUMBER
	,TM_CARET_LINE_TEXT
}