#-*- mode: ruby -*-

group :test, :development do
  gem 'rspec',        '2.13.0'
end

group :test do
  gem 'cucumber',        '2.13.0'
end

gem 'copyright-header', '1.0.3', :group => [:development, :test]

gem 'minitest', '0.5.3', :group => :test

gem 'virtus', '1.0.2', :groups => :test

# vim: syntax=Ruby
